// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Psy5VXOraKOkX3o4iI6lWiT2KBkKRCQ',
    appId: '1:136208769039:web:bb3bec86b565f251ecc37a',
    messagingSenderId: '136208769039',
    projectId: 'chat-up-814f9',
    authDomain: 'chat-up-814f9.firebaseapp.com',
    storageBucket: 'chat-up-814f9.appspot.com',
    measurementId: 'G-X3ZTW0KM9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNlVDflzpCWq8FcmGBveKvkaSX4AuxzD8',
    appId: '1:136208769039:android:b5534cd59d2fbc24ecc37a',
    messagingSenderId: '136208769039',
    projectId: 'chat-up-814f9',
    storageBucket: 'chat-up-814f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS5cvrJPz875ECcTkdvDiubmuwPywnXjk',
    appId: '1:136208769039:ios:ad65338df121bbd2ecc37a',
    messagingSenderId: '136208769039',
    projectId: 'chat-up-814f9',
    storageBucket: 'chat-up-814f9.appspot.com',
    iosClientId: '136208769039-obbjhk7llf3h5sk7oo0nq8qtf4e0v06d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS5cvrJPz875ECcTkdvDiubmuwPywnXjk',
    appId: '1:136208769039:ios:ad65338df121bbd2ecc37a',
    messagingSenderId: '136208769039',
    projectId: 'chat-up-814f9',
    storageBucket: 'chat-up-814f9.appspot.com',
    iosClientId: '136208769039-obbjhk7llf3h5sk7oo0nq8qtf4e0v06d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatUp',
  );
}
